### ISSUE TITLE
Compiling the code

### ISSUE THREAD

**Issue by saeeds255** [swalecko/PoloniexTradeGUI#25]
Hi,
How can I compile this code to use it as an executable .exe file on windows?
I want to edit sourse code an run the new software. 
Thanks

**Comment by swalecko** [comment]
Hi,

you need to clone the repo. 
Then you need to install all the required modules and software:
Qt 5.5.1 or above
Python 3.4.3 or above
PyQT5
Modules: requests, json, urllib

For compiling to get a exe file I am using "pyinstaller".
Install pyinstaller first.
For creating the exe file use this command:
cli: 
change to the path from the cloned repo
command: pyinstaller -w -n PoloTrader -i 1.png.ico -F PoloTrader.pyw

I hope it helps you
